# Generated by Django 5.0.1 on 2024-01-29 09:27

import client_registration.utils
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('natinlacode', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('m', 'مرد'), ('f', 'بانو'), ('o', 'دیگر')], max_length=5)),
                ('image', models.ImageField(upload_to=client_registration.utils.path_client, validators=[client_registration.utils.validat_image])),
                ('created_at_persian', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True)),
                ('updated_at_persian', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('created_at_miladi', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at_miladi', models.DateTimeField(auto_now=True, null=True)),
                ('instagram_id', models.CharField(max_length=100)),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_registration.clienttype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_date_persian', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now)),
                ('is_treatment_order', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_registration.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_registration.service')),
            ],
        ),
        migrations.CreateModel(
            name='RequestRegistrationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_date_persian', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_registration.order')),
            ],
        ),
    ]
