# Generated by Django 5.0.1 on 2024-01-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_registration', '0002_alter_order_order_date_persian_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
