# Generated by Django 5.0.1 on 2024-01-29 10:09

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_registration', '0003_remove_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date_persian',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='requestregistrationitem',
            name='request_date_persian',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now),
        ),
    ]
