# Generated by Django 5.0.1 on 2024-01-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_registration', '0004_alter_order_order_date_persian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
            preserve_default=False,
        ),
    ]
