# Generated by Django 5.0.1 on 2024-01-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_registration', '0005_service_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestRegistrationItem',
        ),
    ]
