# Generated by Django 5.0.1 on 2024-01-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_registration', '0006_delete_requestregistrationitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_treatment_order',
            new_name='is_treatment_complete',
        ),
    ]
