# Generated by Django 5.0.1 on 2024-01-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_registration', '0007_rename_is_treatment_order_order_is_treatment_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
