# Generated by Django 5.0.1 on 2024-01-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_registration', '0009_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
