# Generated by Django 5.0.1 on 2024-02-05 12:49

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_registration', '0011_alter_order_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('follow_date_persian', django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now)),
                ('status', models.CharField(choices=[('con', 'در حال پیگیری'), ('no', 'عدم تمایل جهت مراجعه'), ('yes', 'پذیرش ثبت وقت'), ('not', 'عدم پاسخ')], default='con', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_registration.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_registration.service')),
            ],
        ),
    ]
