# Generated by Django 5.0.1 on 2024-02-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_registration', '0012_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='job',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
